from collections import Counter

from checks.base import SEVERITIES, all_checks


def report(findings) -> str:
    counts = Counter(f.severity for f in findings)
    titles = {check.id: check.title for check in all_checks()}
    lines = [
        "# Data findings",
        "",
        "Generated by `python main.py check`. Every row is produced by a check in",
        "`checks/`, so this file is regenerated rather than edited.",
        "",
        "| severity | count |",
        "| --- | --- |",
    ]
    lines += [f"| {severity} | {counts.get(severity, 0)} |" for severity in SEVERITIES]
    lines.append("")

    for severity in SEVERITIES:
        current = [f for f in findings if f.severity == severity]
        if not current:
            continue
        lines += [f"## {severity} ({len(current)})", ""]
        for check_id in sorted({f.check_id for f in current}):
            rows = [f for f in current if f.check_id == check_id]
            lines += [f"### `{check_id}` ({len(rows)})", "", titles.get(check_id, ""), ""]
            lines += ["| scope | subject | detail |", "| --- | --- | --- |"]
            lines += [f"| {f.scope} | `{f.subject}` | {f.detail} |" for f in rows]
            lines.append("")
    return "\n".join(lines) + "\n"
